import {
  Button,
  Checkbox,
  FormControl,
  FormControlLabel,
  InputLabel,
  MenuItem,
  Select,
  SelectChangeEvent,
} from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';
import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';

import Input from '@/common/input/v1/Input';
import CouponTargetSection, {
  TargetCondition,
} from '@/domain/admin/coupon/section/CouponTargetSection';
import axios from '@/utils/axios';
import { couponTypeToText, newProgramTypeToText } from '@/utils/convert';

interface CouponEditorProps {
  editorMode: 'create' | 'edit';
}

interface CouponInputValue {
  couponType: string;
  programTypeList: string[];
  name: string;
  code: string;
  discount: string;
  time: string;
  startDate: string;
  endDate: string;
}

interface CouponRequestValue {
  couponType: string;
  programTypeList: {
    programType: string;
  }[];
  targetConditionList: TargetCondition[];
  name: string;
  code: string;
  discount: number;
  time: number;
  startDate: string;
  endDate: string;
}

const CouponEditor = ({ editorMode }: CouponEditorProps) => {
  const navigate = useNavigate();
  const params = useParams();
  const queryClient = useQueryClient();

  const [value, setValue] = useState<CouponInputValue>({
    couponType: '',
    programTypeList: [],
    name: '',
    code: '',
    discount: '',
    time: '',
    startDate: '',
    endDate: '',
  });
  const [isAllDiscount, setIsAllDiscount] = useState(false);
  const [isUnlimited, setIsUnlimited] = useState(false);
  const [isAllMembers, setIsAllMembers] = useState(false);
  const [targetConditionList, setTargetConditionList] = useState<
    TargetCondition[]
  >([]);

  const couponId = Number(params.couponId);

  useQuery({
    queryKey: ['coupon', 'admin', couponId],
    queryFn: async () => {
      const res = await axios.get(`/coupon/admin/${couponId}`);
      const data = res.data.data.couponInfo;
      setIsAllDiscount(data.discount === -1);
      setIsUnlimited(data.time === -1);
      setValue({
        couponType: data.couponType,
        programTypeList: data.couponProgramTypeList,
        name: data.name,
        code: data.code,
        discount: data.discount === -1 ? '' : String(data.discount),
        time: data.time === -1 ? '' : String(data.time),
        startDate: data.startDate,
        endDate: data.endDate,
      });
      const conditions = data.targetConditionList ?? [];
      setIsAllMembers(conditions.length === 0);
      setTargetConditionList(conditions);
      return res.data;
    },
    enabled: editorMode === 'edit',
  });

  const addCoupon = useMutation({
    mutationFn: async (value: CouponRequestValue) => {
      const res = await axios.post('/coupon', value);
      return res.data;
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ['coupon'] });
      navigate('/coupons');
    },
    onError: (error) => handleSubmitError(error),
  });

  const editCoupon = useMutation({
    mutationFn: async (value: CouponRequestValue) => {
      const res = await axios.patch(`/coupon/${params.couponId}`, value);
      const data = res.data;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['coupon'] });
      navigate('/coupons');
    },
    onError: (error) => handleSubmitError(error),
  });

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement> | SelectChangeEvent<string>,
  ) => {
    setValue({ ...value, [e.target.name]: e.target.value });
  };

  const handleProgramTypeChange = (
    e: React.ChangeEvent<HTMLInputElement>,
    programType: string,
  ) => {
    if (e.target.checked) {
      setValue({
        ...value,
        programTypeList: [...value.programTypeList, programType],
      });
    } else {
      setValue({
        ...value,
        programTypeList: value.programTypeList.filter(
          (type) => type !== programType,
        ),
      });
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const newValue: CouponRequestValue = {
      couponType: value.couponType,
      programTypeList: value.programTypeList.map((type) => ({
        programType: type,
      })),
      targetConditionList: isAllMembers ? [] : targetConditionList,
      name: value.name,
      code: value.code,
      discount: isAllDiscount ? -1 : Number(value.discount),
      time: isUnlimited ? -1 : Number(value.time),
      startDate: value.startDate,
      endDate: value.endDate,
    };

    if (editorMode === 'create') {
      addCoupon.mutate(newValue);
    } else if (editorMode === 'edit') {
      editCoupon.mutate(newValue);
    }
  };

  const isChallengeAutoGenerated =
    editorMode === 'edit' && value.couponType === 'CHALLENGE';

  const isSubmitDisabled =
    !value.couponType ||
    !value.name ||
    !value.code ||
    (!isAllDiscount && !value.discount) ||
    (!isUnlimited && !value.time) ||
    !value.startDate ||
    !value.endDate;

  const handleSubmitError = (error: Error) => {
    const errorData = (error as AxiosError).response?.data;
    const errorCode = (errorData as { code: string }).code;
    if (errorCode === 'COUPON_400_2') {
      alert('이미 사용 중인 쿠폰 코드입니다.');
    } else if (errorCode === 'COUPON_400_3') {
      alert('쿠폰 코드는 영문 대문자와 숫자로만 구성되어야 합니다.');
    } else if (errorCode === 'COUPON_NOT_FOUND') {
      alert('존재하지 않는 쿠폰입니다.');
    } else if (errorCode === 'COUPON_ISSUE_TARGET_NOT_FOUND') {
      alert('존재하지 않는 프로그램입니다.');
    } else if (errorCode === 'COUPON_ISSUE_TARGET_INVALID') {
      alert('쿠폰 대상 조건이 올바르지 않습니다.');
    }
  };

  return (
    <main className="mx-auto my-12 w-[48rem]">
      <header>
        <h1 className="text-2xl font-semibold">
          {editorMode === 'create' ? '쿠폰 등록' : '쿠폰 수정'}
        </h1>
      </header>
      <form className="mt-6" onSubmit={handleSubmit}>
        <div className="flex flex-col gap-12">
          <div className="flex flex-col flex-wrap gap-3">
            <label className="text-small20 font-semibold">
              쿠폰 타입 <span className="text-system-error">*</span>
            </label>
            <FormControl fullWidth>
              <InputLabel id="couponType">쿠폰 타입</InputLabel>
              <Select
                labelId="couponType"
                id="couponType"
                label="쿠폰 타입"
                name="couponType"
                value={value.couponType}
                onChange={handleChange}
                disabled={isChallengeAutoGenerated}
              >
                {isChallengeAutoGenerated && (
                  <MenuItem value="CHALLENGE">
                    {couponTypeToText.CHALLENGE}
                  </MenuItem>
                )}
                {Object.keys(couponTypeToText)
                  .filter((type) => type !== 'CHALLENGE')
                  .map((type) => (
                    <MenuItem key={type} value={type}>
                      {couponTypeToText[type]}
                    </MenuItem>
                  ))}
              </Select>
            </FormControl>
          </div>
          <div className="flex flex-col flex-wrap gap-1">
            <label htmlFor="program" className="text-small20 font-bold">
              적용 가능 프로그램
            </label>
            <div>
              <FormControlLabel
                control={
                  <Checkbox
                    checked={value.programTypeList.includes('ALL')}
                    onChange={(e) => handleProgramTypeChange(e, 'ALL')}
                  />
                }
                label="전체"
                slotProps={{ typography: { sx: { whiteSpace: 'nowrap' } } }}
              />
              {Object.keys(newProgramTypeToText).map((programType) => (
                <FormControlLabel
                  key={programType}
                  value={programType}
                  control={
                    <Checkbox
                      checked={value.programTypeList.includes(programType)}
                      onChange={(e) => handleProgramTypeChange(e, programType)}
                    />
                  }
                  label={newProgramTypeToText[programType]}
                  slotProps={{ typography: { sx: { whiteSpace: 'nowrap' } } }}
                />
              ))}
            </div>
          </div>
          <div className="flex flex-col flex-wrap gap-4">
            <div className="flex items-end justify-between">
              <label className="text-small20 font-bold">
                발급 대상
                <p className="text-xxsmall12 mt-1.5 font-normal text-gray-400">
                  쿠폰을 사용할 수 있는 대상을 <strong>결제·수강 이력</strong>{' '}
                  기준으로 설정합니다. (다중 선택 가능)
                </p>
              </label>
              <FormControlLabel
                control={
                  <Checkbox
                    checked={isAllMembers}
                    onChange={() => setIsAllMembers((p) => !p)}
                    size="small"
                  />
                }
                label="회원 전체 발급 (등록형 쿠폰)"
              />
            </div>
            <div
              className={isAllMembers ? 'pointer-events-none opacity-45' : ''}
            >
              <CouponTargetSection
                value={targetConditionList}
                onChange={setTargetConditionList}
              />
            </div>
          </div>
          {/* <div className="ml-4 flex items-center">
            <label className="w-[8rem] font-medium">프로그램 분류</label>
            <FormControlLabel
              control={
                <Checkbox
                  checked={value.programTypeList.includes('ALL')}
                  onChange={(e) => handleProgramTypeChange(e, 'ALL')}
                />
              }
              label="전체"
            />
            {Object.keys(newProgramTypeDetailToText).map((programType) => (
              <FormControlLabel
                key={programType}
                value={programType}
                control={
                  <Checkbox
                    checked={value.programTypeList.includes(programType)}
                    onChange={(e) => handleProgramTypeChange(e, programType)}
                  />
                }
                label={newProgramTypeDetailToText[programType]}
              />
            ))}
          </div>
          <div className="ml-4 flex items-center">
            <label className="w-[8rem] font-medium">id</label>
            <FormControlLabel
              control={
                <Checkbox
                  checked={value.programTypeList.includes('ALL')}
                  onChange={(e) => handleProgramTypeChange(e, 'ALL')}
                />
              }
              label="전체"
            />
            <Input
              label="id"
              name="id"
              value={''}
              fullWidth={false}
              className="flex-1"
              // onChange={handleChange}
            />
          </div> */}
          <div className="flex flex-col flex-wrap gap-4">
            <label className="text-small20 font-bold">
              쿠폰 정보 <span className="text-system-error">*</span>
            </label>
            <div className="flex flex-col flex-wrap gap-3">
              <Input
                label="쿠폰명"
                name="name"
                value={value.name}
                onChange={handleChange}
              />
              <Input
                label="쿠폰 코드"
                name="code"
                value={value.code}
                onChange={handleChange}
              />
              <div className="flex items-center justify-between">
                <FormControlLabel
                  control={<Checkbox />}
                  label="전액"
                  checked={isAllDiscount}
                  onChange={() => {
                    const next = !isAllDiscount;
                    setIsAllDiscount(next);
                    if (next) setValue({ ...value, discount: '' });
                  }}
                  className="h-[3.5rem] w-[8rem]"
                />
                <Input
                  type="number"
                  label="쿠폰 금액"
                  fullWidth={false}
                  className="flex-1"
                  name="discount"
                  value={value.discount === '-1' ? '' : value.discount}
                  onChange={handleChange}
                  disabled={isAllDiscount}
                />
              </div>
              <div className="flex items-center justify-between">
                <FormControlLabel
                  control={<Checkbox />}
                  label="무제한"
                  checked={isUnlimited}
                  onChange={() => {
                    const next = !isUnlimited;
                    setIsUnlimited(next);
                    if (next) setValue({ ...value, time: '' });
                  }}
                  className="h-[3.5rem] w-[8rem]"
                />
                <Input
                  type="number"
                  label="사용 가능 횟수"
                  fullWidth={false}
                  className="flex-1"
                  name="time"
                  value={value.time === '-1' ? '' : value.time}
                  onChange={handleChange}
                  disabled={isUnlimited}
                />
              </div>
              <div className="flex">
                <label
                  htmlFor="startDate"
                  className="flex h-[3.5rem] w-[8.3rem] items-center text-center"
                >
                  시작 일자
                </label>
                <input
                  id="startDate"
                  type="datetime-local"
                  name="startDate"
                  value={value.startDate}
                  onChange={handleChange}
                  className="border-neutral-70 rounded-xxs flex-1 cursor-pointer border p-4"
                />
              </div>
              <div className="flex">
                <label
                  htmlFor="endDate"
                  className="flex h-[3.5rem] w-[8.3rem] items-center text-center"
                >
                  마감 일자
                </label>
                <input
                  id="endDate"
                  type="datetime-local"
                  name="endDate"
                  value={value.endDate}
                  onChange={handleChange}
                  className="border-neutral-70 rounded-xxs flex-1 cursor-pointer border p-4"
                />
              </div>
            </div>
          </div>
        </div>
        <div className="mt-10 flex justify-end gap-2">
          <Button
            type="submit"
            size="large"
            variant="contained"
            color="primary"
            disabled={isSubmitDisabled}
          >
            {editorMode === 'create' ? '쿠폰 등록' : '수정 완료'}
          </Button>
          <Button
            type="button"
            size="large"
            variant="outlined"
            onClick={() => navigate(-1)}
          >
            취소
          </Button>
        </div>
      </form>
    </main>
  );
};

export default CouponEditor;
