import { ProgramContent, ProgramId } from '../types/types';

export const PROGRAMS: Record<ProgramId, ProgramContent> = {
  experience: {
    id: 'experience',
    title: '기필코 경험정리 챌린지',
    subtitle: '마인드맵 · STAR로 경험을 구조화',
    target: '취준을 막 시작해 경험 정리부터 필요한 분',
    duration: '2주',
    deliverable: 'STAR 기법 기반 경험정리본',
    feedback: '참여 인원 중 일부 선발 (2~4회차)',
    curriculum: [
      '경험 나열 및 소재 수집',
      '대학/교내 활동 경험 정리',
      '교외 활동 경험 정리',
      '일상 및 커리어 경험 정리',
      '경험 정리 완성 (마인드맵 · STAR)',
    ],
    features: ['마인드맵, STAR 기법 활용'],
    plans: [
      {
        id: 'basic',
        name: '베이직',
        price: '10,000원 (환급 기준)',
        note: '환급형',
      },
    ],
  },
  resume: {
    id: 'resume',
    title: '이력서 1주 완성 챌린지',
    subtitle: '경험 정리 후 채용 관점 구조화',
    target: '빠르게 이력서를 완성해야 하는 분',
    duration: '1주',
    deliverable: '멘토 피드백 반영 최종 이력서 + 합격자 10선 예시',
    feedback: '스탠다드 1회',
    curriculum: [
      '경험 정리와 소재 선별',
      '경험 분석 및 역량 강조',
      '채용 관점 구조화',
      '이력서 완성',
    ],
    features: ['합격 이력서 10선 제공'],
    plans: [
      { id: 'basic', name: '베이직', price: '10,000원 (환급 기준)' },
      { id: 'standard', name: '스탠다드', price: '29,900원' },
    ],
  },
  coverLetter: {
    id: 'coverLetter',
    title: '자기소개서 2주 완성 챌린지',
    subtitle: '직무 분석부터 마스터 자소서까지',
    target: '자기소개서를 처음 만들거나 고도화하려는 분',
    duration: '2주',
    deliverable: '마스터 자기소개서 + 맞춤형 합격자 자소서 예시',
    feedback: '스탠다드 1회 · 프리미엄 2회',
    curriculum: [
      '직무 분석',
      '경험 분석',
      '자기소개서 기초',
      '자기소개서 발전',
      '자기소개서 완성 (K-STAR-K, 3WHY)',
    ],
    features: ['K-STAR-K 프레임워크 · 3WHY 사용'],
    plans: [
      { id: 'basic', name: '베이직', price: '38,500원' },
      { id: 'standard', name: '스탠다드', price: '64,000원' },
      { id: 'premium', name: '프리미엄', price: '89,000원' },
    ],
  },
  portfolio: {
    id: 'portfolio',
    title: '포트폴리오 2주 완성 챌린지',
    subtitle: '직무 맞춤 포트폴리오 설계·작성',
    target: '지원 직무에 포트폴리오가 필요한 분',
    duration: '2주',
    deliverable: '마스터 포트폴리오 + 합격자 포트폴리오 예시',
    feedback: '스탠다드 1회 · 프리미엄 2회',
    curriculum: [
      '경험 분석',
      '포트폴리오 목차 선정',
      '포트폴리오 기초 작성',
      '포트폴리오 발전',
      '포트폴리오 완성 및 점검',
    ],
    features: ['구조화 템플릿 제공'],
    plans: [
      { id: 'basic', name: '베이직', price: '48,500원' },
      { id: 'standard', name: '스탠다드', price: '78,000원' },
      { id: 'premium', name: '프리미엄', price: '98,500원' },
    ],
  },
  enterpriseCover: {
    id: 'enterpriseCover',
    title: '대기업 자기소개서 완성 챌린지',
    subtitle: '산업·기업 분석과 공채 문항 대비',
    badge: '환급금 없음',
    target: '대기업 맞춤 경험정리·자기소개서를 작성하고 싶은 분',
    duration: '3주',
    deliverable:
      '대기업 맞춤 경험정리본, 자기소개서, 산업/기업분석 특강 자료 및 템플릿',
    feedback: '스탠다드 2회 · 프리미엄 4회',
    curriculum: [
      '기업/산업 분석',
      '직무 분석',
      '경험 분석 + 서면 멘토링',
      '직무 역량 답변 + 서면 멘토링',
      '지원동기 답변 + 서면 멘토링',
      '자기소개서 완성 + Live 멘토링',
    ],
    features: ['대기업 현직자 특강 4회', '기업별 맞춤 분석 심화 커리큘럼'],
    plans: [
      { id: 'basic', name: '베이직', price: '113,500원', note: '환급금 없음' },
      {
        id: 'standard',
        name: '스탠다드',
        price: '164,000원',
        note: '환급금 없음',
      },
      {
        id: 'premium',
        name: '프리미엄',
        price: '214,000원',
        note: '환급금 없음',
      },
    ],
  },
  marketingAllInOne: {
    id: 'marketingAllInOne',
    title: '마케팅 서류 완성 올인원 챌린지',
    subtitle: '현직자와 경험정리·자소서·포트폴리오 완성',
    badge: '환급금 없음',
    target: '마케팅 직무 서류를 한 번에 완성하고 싶은 분',
    duration: '4주',
    deliverable:
      '경험정리 + 자기소개서 + 포트폴리오 완성, 마케팅 합격 이력서/포트폴리오 예시',
    feedback: '스탠다드 1회 · 프리미엄 2회',
    curriculum: [
      '직무 탐색',
      '경험 정리',
      '컨셉 설정',
      '자기소개서 작성',
      '포트폴리오 작성 및 완성',
    ],
    features: [
      '단계별 마케팅 취업 자료/템플릿',
      '마케팅 실무 역량 Class 4회 (Figma·GA·Meta)',
      '마케팅 현직자 세미나 4회',
      'CMO/CPO 필수역량 세미나',
    ],
    plans: [
      { id: 'basic', name: '베이직', price: '99,000원', note: '환급금 없음' },
      {
        id: 'standard',
        name: '스탠다드',
        price: '149,000원',
        note: '환급금 없음',
      },
      {
        id: 'premium',
        name: '프리미엄',
        price: '179,000원',
        note: '환급금 없음',
      },
    ],
  },
  hrAllInOne: {
    id: 'hrAllInOne',
    title: 'HR 서류 완성 올인원 챌린지',
    subtitle: 'HR 현직자와 경험정리·자소서·포트폴리오 완성',
    badge: '환급금 없음',
    target: 'HR 직무 서류를 한 번에 완성하고 싶은 분',
    duration: '3주',
    deliverable:
      '경험정리 + 자기소개서 + 포트폴리오 완성, HR 합격 이력서/포트폴리오 예시',
    feedback: '스탠다드 1회 · 프리미엄 2회',
    curriculum: [
      '직무 탐색',
      '경험 정리',
      '컨셉 잡기',
      '자기소개서 작성',
      '포트폴리오 작성 및 완성',
    ],
    features: [
      'HR 현직자 세미나 4회 (채용/조직/People Analytics/서류 분석)',
      'HR 세부 직무 학습 자료',
    ],
    plans: [
      { id: 'basic', name: '베이직', price: '89,000원', note: '환급금 없음' },
      {
        id: 'standard',
        name: '스탠다드',
        price: '123,000원',
        note: '환급금 없음',
      },
      {
        id: 'premium',
        name: '프리미엄',
        price: '156,000원',
        note: '환급금 없음',
      },
    ],
  },
};
